config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  root 'home#index'
  get 'home/about'
  post "/" => 'home#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   # @stock = StockQuote::Stock.quote("aapl")
   
   if params[:id] == ""
    @nothing = "Hey, you forget to enter symbol"
    elsif
        if params[:id]
            
            #@stock = StockQuote::Stock.quote("aapl,tsla")
        
            # I also tried use this code to show the content of StockQuote in hash format but I can't extract it
            @stock  = StockQuote::Stock.json_quote(params[:id])
        end
   end
   rescue JSON::ParserError
    []
  end
  
  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
    
    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stocker", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", home_about_path %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to "List Stocks", stocks_path %></li>
          <li><%= link_to "Add Stocks", new_stock_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Update Profile", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>This is my first Rails App!</p>

app/views/home/index.html.erb
<%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'id', nil, placeholder: 'Enter Company Ticker Symbol', size: 50 %>
    <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

</br>

<% if @stock == nil %>
    <strong>Sorry,  doesn't seem to be an actual stock...</strong>
<% elsif @stock %>
    <strong>Company Name: </strong> <%= @stock['name'] %> <br>
     <strong>Current Ask: </strong> <%= @stock['l'] %> <br>
    <strong>Earnings Per Share: </strong> <%= @stock['eps'] %> <br>
    <strong>Price/Earning Ratio: </strong> <%= @stock['pe'] %> <br>
    <strong>Market Cap: </strong> <%= @stock['mc'] %> <br>
    <strong>Previous Close: </strong> <%= @stock['l'] %> <br>
    <strong>Stock Open: </strong> <%= @stock['op'] %> <br>
    <strong>Day's Range: </strong> <%= @stock['lo'] %> - <%= @stock['hi'] %><br>
    <strong>Year High: </strong> <%= @stock['hi52'] %> <br>
    <strong>Year Low: </strong> <%= @stock['lo52'] %> <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stocker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
<%= render 'home/navbar' %>

<div class="container">
  
  <%= render 'home/flash' %>
       
  <%= yield %>
</div>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %><br>
    <%= f.text_field :ticker %>
  </div>
  <div class="field">
    <%= f.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Current Worth</th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
    <% @stock_quote =  StockQuote::Stock.json_quote(stock.ticker) %>
      <% if stock.user_id == current_user.id %>
      <tr>
        <td><%= link_to @stock_quote['name'], stock  %></td>
        <td><%= stock.ticker %></td>
        <td><%= @stock_quote['l'] %></td>
         <td><%= @stock_quote['mc'] %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path, class: "btn btn-default" %>
<br><br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Stock Quote Lookup</h3>
  </div>
  <div class="panel-body">
    <%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'id', nil, placeholder: 'Enter Company Ticker Symbol', size: 50 %>
    <%= submit_tag 'Lookup Stock Quote', class: "btn btn-default" %>
<% end %>
  </div>
</div>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% begin %>
  <% @stock = StockQuote::Stock.quote(@stock.ticker)%>
<% rescue StandardError %>
 Hello Error
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @stock.name %> - <%= @stock.symbol %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-4">
     <h1>$  <%= @stock.l %> </h1>
    <strong>Earnings Per Share: </strong> <%= @stock.eps %> <br>
    <strong>Price/Earning Ratio: </strong> <%= @stock.pe %> <br>
    <strong>Market Cap: </strong> <%= @stock.mc %> <br>
    <strong>Stock Open: </strong> <%= @stock.op %> <br>
    <strong>Day's Range: </strong> <%= @stock.lo %> - <%= @stock.lo %><br>
    <strong>Year High: </strong> <%= @stock.hi52 %> <br>
    <strong>Year Low: </strong> <%= @stock.lo52 %> <br><br>
    </div>
    <div class="col-md-8"><br>
      <p align="justify"><%= @stock.summary[0]['overview'] %></p>
    </div>
  </div>
  <div class="panel-footer"><%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Remove Stock', stock_path(@stock), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', stocks_path %>
</div>
</div>